copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop1\in.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store1_in.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop1\out.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store1_out.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop2\in.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store2_in.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop2\out.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store2_out.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop3\in.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store3_in.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop3\out.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store3_out.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop4\in.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store4_in.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop4\out.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store4_out.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop5\in.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store5_in.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop5\out.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store5_out.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop6\in.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store6_in.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop6\out.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store6_out.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop7\in.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store7_in.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop7\out.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store7_out.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop8\in.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store8_in.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop8\out.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store8_out.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop9\in.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store9_in.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop9\out.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store9_out.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop10\in.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store10_in.txt
copy C:\Users\ivanb\Desktop\R\Final_test\My_shop\Shop10\out.txt C:\Users\ivanb\Desktop\R\Final_test\My_shop\Analysis\store10_out.txt
